### ISSUE TITLE
Missing recent data in /data_tables/testing_data/time_series_covid19_US.csv

### ISSUE THREAD

**Issue by simonstl** [govex/COVID-19#448]
In both GitHub and in the repository I cloned locally, the CSV file at https://github.com/govex/COVID-19/blob/master/data_tables/testing_data/time_series_covid19_US.csv only reports through March 2nd.  

It reports daily commits in the History, so I'm not sure why it's missing data.

Thank you,
Simon St.Laurent

**Comment by dje1591** [comment]
It appears this issue is also affecting the Daily automated CRC data bot US vaccine time series update.

**Comment by jmh530** [comment]
The US vaccine time series ([https://github.com/govex/COVID-19/blob/master/data_tables/vaccine_data/us_data/time_series/vaccine_data_us_timeline.csv](https://github.com/govex/COVID-19/blob/master/data_tables/vaccine_data/us_data/time_series/vaccine_data_us_timeline.csv)) has also not been updated since 3/22 (as of 3/24 afternoon EST).

**Comment by simonstl** [comment]
Looks okay now, at least for the time_series_covid19_US file.  Thanks!
